services:
  api:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.api
    image: localhost/api:0.0.1
    volumes: 
      - ./apps/db/data:/apps/db/data
    env_file:
      - ./apps/server/.env
    network_mode: host

  client:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.client
    image: localhost/client:0.0.1
    env_file:
      - ./apps/client/.env
    network_mode: host
  
  workers:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.workers
    image: localhost/workers:0.0.1
    volumes: 
      - ./apps/db/data:/apps/db/data
    env_file:
      - ./apps/workers/.env
    network_mode: host


  meta-reverse-proxy:
    build:
      dockerfile: ./infra/meta-reverse-proxy/Dockerfile
    image: localhost/meta-reverse-proxy:0.0.1
    restart: unless-stopped
    env_file:
      - ./apps/client/.env
      - ./apps/server/.env
      - ./apps/workers/.env
    network_mode: host

  # client-reverse-proxy:
  #   build:
  #     dockerfile: ./infra/client-reverse-proxy/Dockerfile
  #   image: localhost/client-reverse-proxy:0.0.1
  #   restart: unless-stopped
  #   env_file:
  #     - ./apps/client/.env
  #   network_mode: host

  # api-reverse-proxy:
  #   build:
  #     dockerfile: ./infra/api-reverse-proxy/Dockerfile
  #   image: localhost/api-reverse-proxy:0.0.1
  #   restart: unless-stopped
  #   env_file:
  #     - ./apps/server/.env
  #   network_mode: host

  # workers-reverse-proxy:
  #   build:
  #     dockerfile: ./infra/workers-reverse-proxy/Dockerfile
  #   image: localhost/workers-reverse-proxy:0.0.1
  #   restart: unless-stopped
  #   env_file:
  #     - ./apps/workers/.env
  #   network_mode: host


volumes:
  caddy_data:
  caddy_config:
