/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardAccountRouteRouteImport } from './routes/dashboard/account/route'
import { Route as DashboardAccountPasskeysRouteImport } from './routes/dashboard/account/passkeys'
import { Route as DashboardAccountEmailsRouteImport } from './routes/dashboard/account/emails'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountRouteRoute = DashboardAccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountPasskeysRoute =
  DashboardAccountPasskeysRouteImport.update({
    id: '/passkeys',
    path: '/passkeys',
    getParentRoute: () => DashboardAccountRouteRoute,
  } as any)
const DashboardAccountEmailsRoute = DashboardAccountEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => DashboardAccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/account': typeof DashboardAccountRouteRouteWithChildren
  '/dashboard/account/emails': typeof DashboardAccountEmailsRoute
  '/dashboard/account/passkeys': typeof DashboardAccountPasskeysRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/account': typeof DashboardAccountRouteRouteWithChildren
  '/dashboard/account/emails': typeof DashboardAccountEmailsRoute
  '/dashboard/account/passkeys': typeof DashboardAccountPasskeysRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/account': typeof DashboardAccountRouteRouteWithChildren
  '/dashboard/account/emails': typeof DashboardAccountEmailsRoute
  '/dashboard/account/passkeys': typeof DashboardAccountPasskeysRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard/account'
    | '/dashboard/account/emails'
    | '/dashboard/account/passkeys'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard/account'
    | '/dashboard/account/emails'
    | '/dashboard/account/passkeys'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/login'
    | '/register'
    | '/dashboard/account'
    | '/dashboard/account/emails'
    | '/dashboard/account/passkeys'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/passkeys': {
      id: '/dashboard/account/passkeys'
      path: '/passkeys'
      fullPath: '/dashboard/account/passkeys'
      preLoaderRoute: typeof DashboardAccountPasskeysRouteImport
      parentRoute: typeof DashboardAccountRouteRoute
    }
    '/dashboard/account/emails': {
      id: '/dashboard/account/emails'
      path: '/emails'
      fullPath: '/dashboard/account/emails'
      preLoaderRoute: typeof DashboardAccountEmailsRouteImport
      parentRoute: typeof DashboardAccountRouteRoute
    }
  }
}

interface DashboardAccountRouteRouteChildren {
  DashboardAccountEmailsRoute: typeof DashboardAccountEmailsRoute
  DashboardAccountPasskeysRoute: typeof DashboardAccountPasskeysRoute
}

const DashboardAccountRouteRouteChildren: DashboardAccountRouteRouteChildren = {
  DashboardAccountEmailsRoute: DashboardAccountEmailsRoute,
  DashboardAccountPasskeysRoute: DashboardAccountPasskeysRoute,
}

const DashboardAccountRouteRouteWithChildren =
  DashboardAccountRouteRoute._addFileChildren(
    DashboardAccountRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardAccountRouteRoute: typeof DashboardAccountRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRouteRoute: DashboardAccountRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
